version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    network_mode: host

  db:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: db
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: user-manager
    network_mode: host
