version: '3.7'

services:
  api:
    container_name: nest-api
    build: .
    ports:
      - '3333:3333'
    volumes:
      - .:/home/api

  mongodb:
    container_name: mondodb
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: user-manager
