version: '3.8'

services:
  # api:
  #   container_name: api-container
  #   build: .
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/home/node/app
  #   network_mode: host

  db:
    container_name: db-container
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: user-manager
    # network_mode: host
